/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.junichi11.netbeans.modules.backlog.query.ui;

/**
 *
 * @author junichi11
 */
public class NotificationPanel extends javax.swing.JPanel {

    public static final String PROPERTY_MARK_AS_READ = "notification.mark.as.read"; // NOI18N
    public static final String PROPERTY_MARK_ALL_AS_READ = "notification.mark.all.as.read"; // NOI18N
    private final String comment;
    private final long id;

    /**
     * Creates new form NotificationPanel
     */
    public NotificationPanel() {
        this("", -1); // NOI18N
    }

    public NotificationPanel(String comment, long id) {
        this.comment = comment;
        this.id = id;
        initComponents();
        setComment(comment);
    }

    public long getNotificationId() {
        return id;
    }

    public String getComment() {
        return comment;
    }

    private void setComment(String comment) {
        commentTextPane.setText(comment);
    }

    void markAsReadPressed() {
        firePropertyChange(PROPERTY_MARK_AS_READ, null, null);
    }

    void markAllAsReadPressed() {
        firePropertyChange(PROPERTY_MARK_ALL_AS_READ, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        markAsReadButton = new javax.swing.JButton();
        markAllAsReadButton = new javax.swing.JButton();
        commentLabel = new javax.swing.JLabel();
        commentScrollPane = new javax.swing.JScrollPane();
        commentTextPane = new javax.swing.JTextPane();

        setOpaque(false);

        org.openide.awt.Mnemonics.setLocalizedText(markAsReadButton, org.openide.util.NbBundle.getMessage(NotificationPanel.class, "NotificationPanel.markAsReadButton.text")); // NOI18N
        markAsReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAsReadButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(markAllAsReadButton, org.openide.util.NbBundle.getMessage(NotificationPanel.class, "NotificationPanel.markAllAsReadButton.text")); // NOI18N
        markAllAsReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAllAsReadButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(commentLabel, org.openide.util.NbBundle.getMessage(NotificationPanel.class, "NotificationPanel.commentLabel.text")); // NOI18N

        commentTextPane.setEditable(false);
        commentScrollPane.setViewportView(commentTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(markAsReadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markAllAsReadButton))
            .addComponent(commentLabel)
            .addComponent(commentScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(commentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markAsReadButton)
                    .addComponent(markAllAsReadButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void markAsReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAsReadButtonActionPerformed
        markAsReadPressed();
    }//GEN-LAST:event_markAsReadButtonActionPerformed

    private void markAllAsReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAllAsReadButtonActionPerformed
        markAllAsReadPressed();
    }//GEN-LAST:event_markAllAsReadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commentLabel;
    private javax.swing.JScrollPane commentScrollPane;
    private javax.swing.JTextPane commentTextPane;
    private javax.swing.JButton markAllAsReadButton;
    private javax.swing.JButton markAsReadButton;
    // End of variables declaration//GEN-END:variables
}
